// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-11-15 20:07:35.516876 +0300 MSK m=+0.022725735

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "This is Plasma-Client implementation",
        "title": "Swagger History API",
        "contact": {
            "name": "API Support",
            "email": "nk@bankexfoundation.org, kk@bankexfoundation.org, ig@bankexfoundation.org, av@bankexfoundation.org"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "0.0.1"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/SetMyTx": {
            "post": {
                "description": "Put your tx by tx Id",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Put your tx by tx Id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tx",
                        "name": "tx",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/responses.SuccessResponse"
                            }
                        }
                    }
                }
            }
        },
        "/getHistoryPart": {
            "get": {
                "description": "Return History of blocks",
                "produces": [
                    "application/json"
                ],
                "summary": "Return History of blocks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/responses.HistoryResponse"
                            }
                        }
                    }
                }
            }
        },
        "/getMyTx": {
            "get": {
                "description": "Return Tx by tx Id",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Return Tx by tx Id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tx",
                        "name": "tx",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/responses.TxResponse"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "responses.HistoryResponse": {
            "type": "object",
            "properties": {
                "History": {
                    "type": "string",
                    "example": "1c8d54df80c03a56b5470d164c49f823108f96a67d020e4c677810c9a10b1ca7"
                }
            }
        },
        "responses.SuccessResponse": {
            "type": "object",
            "properties": {
                "Status": {
                    "type": "string",
                    "example": "Ok"
                }
            }
        },
        "responses.TxResponse": {
            "type": "object",
            "properties": {
                "Tx": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
