basePath: '{{.BasePath}}'
definitions:
  responses.AssetsResponse:
    properties:
      assets:
        example: 1c8d54df80c03a56b5470d164c49f823108f96a67d020e4c677810c9a10b1ca7
        type: string
    type: object
host: '{{.Host}}'
info:
  contact:
    email: nk@bankexfoundation.org, kk@bankexfoundation.org, ig@bankexfoundation.org,
      av@bankexfoundation.org
    name: API Support
  description: This is Plasma-Client implementation
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Swagger History API
  version: 0.0.1
paths:
  /getHistoryPart:
    get:
      description: Return History of blocks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.AssetsResponse'
            type: array
      summary: Return History of blocks
swagger: "2.0"
