basePath: '{{.BasePath}}'
definitions:
  responses.HistoryResponse:
    properties:
      History:
        example: 1c8d54df80c03a56b5470d164c49f823108f96a67d020e4c677810c9a10b1ca7
        type: string
    type: object
  responses.SuccessResponse:
    properties:
      Status:
        example: Ok
        type: string
    type: object
  responses.TxResponse:
    properties:
      Tx:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact:
    email: nk@bankexfoundation.org, kk@bankexfoundation.org, ig@bankexfoundation.org,
      av@bankexfoundation.org
    name: API Support
  description: This is Plasma-Client implementation
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Swagger History API
  version: 0.0.1
paths:
  /SetMyTx:
    post:
      consumes:
      - text/plain
      description: Put your tx by tx Id
      parameters:
      - description: tx
        in: path
        name: tx
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.SuccessResponse'
            type: array
      summary: Put your tx by tx Id
  /getHistoryPart:
    get:
      description: Return History of blocks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.HistoryResponse'
            type: array
      summary: Return History of blocks
  /getMyTx:
    get:
      consumes:
      - text/plain
      description: Return Tx by tx Id
      parameters:
      - description: tx
        in: path
        name: tx
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.TxResponse'
            type: array
      summary: Return Tx by tx Id
swagger: "2.0"
